### ISSUE TITLE
tableParser 오류 발생에 대하여

### ISSUE THREAD

**Issue by aaei924** [LiteHell/js-namumark#4]
js-namumark-master/parsers/tableParser.js:11
        rowspan += parseInt(/^\|([0-9]+)$/.exec(optionContent)[1] || /^\^\|([0-9]+)$/.exec(optionContent)[1] || /^v\|([0-9]+)$/.exe(optionContent)[1]);
                                                              ^

TypeError: Cannot read property '1' of null
    at parseOptionBracket (/home/ubuntu/js-namumark-master/parsers/tableParser.js:11:63)
    at module.exports (/home/ubuntu/js-namumark-master/parsers/tableParser.js:124:105)
    at doParse (/home/ubuntu/js-namumark-master/index.js:44:80)
    at Immediate.<anonymous> (/home/ubuntu/js-namumark-master/index.js:180:43)

텍스트를 작성하고 '저장' 버튼을 눌렀더니 이런 오류가 발생하면서 프로세스가 중단됐습니다.

**Comment by LiteHell** [comment]
해당 오류를 발생시킨 위키텍스트를 알 수 있을까요?

**Comment by aaei924** [comment]
아마 나무위키 문법 도움말로 기억합니다.

**Comment by LiteHell** [comment]
지금 파서를 재작성하고 있으니, 개발중에 참고하도록 하겠습니다.
